# This file should contain all the record creation needed to seed the database
# with its default values.
# The data can then be loaded with the rails db:seed command (or created
# alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' },
#                          { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# rubocop:disable Metrics/MethodLength, Naming/VariableNumber

def sake_create_0
  Sake.create!(
    alcohol: 17.0,
    aminosando: nil,
    aroma_impression: "完熟メロンのような香り",
    aroma_value: 4,
    awa: "",
    bindume_date: Date.new(2020, 8),
    bottle_level: :sealed,
    brew_year: Date.new(2019),
    color: "うっすら黄色",
    genryomai: "",
    hiire: :mae_hiire,
    kakemai: "",
    kobo: "",
    kura: "金虎酒造株式会社",
    moto: :unknown,
    name: "本醸造",
    nigori: "",
    nihonshudo: nil,
    note: "秋刀魚焼きや赤から鍋の強い味にも合う。",
    photos: [],
    price: 1320,
    roka: "",
    sando: nil,
    season: "ひやおろし",
    seimai_buai: 60,
    shibori: "",
    size: 720,
    taste_impression: "口ですぐに完熟な甘さと強い旨さがくる。そこをアルコールと苦さによる辛さが舌を強くしっかり洗い流す。味はガッツリしてるがキレもよい。",
    taste_value: 5,
    todofuken: "愛知県",
    tokutei_meisho: :junmai,
    warimizu: :unknown,
  )
end

def sake_create_1
  Sake.create!(
    alcohol: 15.0,
    aminosando: nil,
    name: "特別本醸造 別仕込 萩の鶴 ねこラベル",
    kura: "萩野酒造株式会社",
    photos: [],
    bindume_date: Date.new(2020, 6),
    brew_year: Date.new(2019, 7),
    todofuken: "宮城県",
    taste_value: 3,
    aroma_value: 5,
    nihonshudo: nil,
    sando: nil,
    aroma_impression: "",
    color: "",
    taste_impression: "",
    nigori: "",
    awa: "",
    tokutei_meisho: :junmai_ginjo,
    genryomai: "美山錦",
    kakemai: "",
    kobo: "",
    season: "",
    warimizu: :unknown,
    moto: :unknown,
    seimai_buai: 50,
    roka: "",
    shibori: "",
    note: "",
    bottle_level: :sealed,
    hiire: :namanama,
    price: 3080,
    size: 1800,
  )
end

def sake_create_2
  Sake.create!(
    name: "千瓢原酒",
    kura: "水谷酒造",
    photos: [],
    bindume_date: Date.new(2019, 12),
    brew_year: Date.new(2019, 7),
    todofuken: "愛知県",
    nihonshudo: nil,
    sando: nil,
    aroma_impression: "",
    color: "",
    taste_impression: "",
    nigori: "",
    awa: "",
    tokutei_meisho: :none,
    genryomai: "",
    kakemai: "",
    kobo: "",
    alcohol: 21,
    aminosando: nil,
    season: "",
    warimizu: :genshu,
    moto: :unknown,
    seimai_buai: nil,
    roka: "",
    shibori: "",
    note: "",
    bottle_level: :sealed,
    hiire: :namanama,
    price: nil,
    size: 1800,
  )
end

def sake_create_3
  Sake.create!(
    name: "黄金澤 山廃純米酒 うすにごり原酒",
    kura: "合名会社 川敬商店",
    photos: [],
    bottle_level: :sealed,
    bindume_date: Date.new(2020, 6),
    brew_year: Date.new(2019, 7),
    todofuken: "宮城県",
    alcohol: 16.0,
    size: 1800,
    tokutei_meisho: :junmai,
    warimizu: :genshu,
    moto: :yamahai,
    nigori: "うすにごり",
    hiire: :unknown,
    seimai_buai: 60,
    nihonshudo: nil,
    sando: nil,
    aroma_impression: "",
    color: "",
    taste_impression: "",
    awa: "",
    genryomai: "",
    kakemai: "",
    kobo: "",
    aminosando: nil,
    season: "",
    roka: "",
    shibori: "",
    note: "",
    price: 2807,
  )
end

# 笹井酒造
def sake_create_4
  Sake.create!(
    alcohol: 16.0,
    aminosando: nil,
    aroma_impression: "酸や複雑な旨味の香り",
    aroma_value: 4,
    awa: "",
    bindume_date: Date.new(2020, 8),
    bottle_level: :opened,
    brew_year: Date.new(2019),
    color: "無色",
    genryomai: "ひとごこち",
    hiire: :namanama,
    kakemai: "ひとごこち",
    kobo: "長野酵母",
    kura: "笹井酒造株式会社",
    moto: :yamahai,
    name: "笹の誉 純米吟醸山廃仕込み 生 ひとごこち",
    nigori: "",
    nihonshudo: nil,
    note: "鶏肉に合わせてうまい！",
    photos: [],
    price: 3410,
    roka: "",
    sando: nil,
    season: "",
    seimai_buai: 55,
    shibori: "",
    size: 1800,
    taste_impression: "味はクリアな甘さにドドドドっと旨味がしっかり乗る。豆のような甘さ。山廃にしてはあんまや酸っぽくない味。最後は舌に苦味を残して、クドすぎない潔くほどよいキレ。",
    taste_value: 3,
    todofuken: "長野県",
    tokutei_meisho: :junmai_ginjo,
    warimizu: :kasui,
  )
end

def sake_create_5
  Sake.create!(
    alcohol: 17.0,
    aminosando: nil,
    aroma_impression: "木や薫香を感じる",
    aroma_value: 2,
    awa: "",
    bindume_date: Date.new(2020, 8),
    bottle_level: :sealed,
    brew_year: Date.new(2019),
    color: "黄色",
    genryomai: "ひとごこち",
    hiire: :namanama,
    kakemai: "ひとごこち",
    kobo: "協会901号酵母",
    kura: "笹井酒造株式会社",
    moto: :unknown,
    name: "笹の誉 特別純米酒 直汲み生 ひとごこち",
    nigori: "",
    nihonshudo: -2,
    note: "",
    photos: [],
    price: nil,
    roka: "",
    sando: nil,
    season: "",
    seimai_buai: 55,
    shibori: "",
    size: 720,
    taste_impression: "ヒネ、旨味、苦味がドンとくる。ちょっと味わいが強いお酒だけど、奥にある酸がほどよい余韻で終わらせる。生と古酒が一緒にくる、すごい。",
    taste_value: 5,
    todofuken: "長野県",
    tokutei_meisho: :junmai,
    warimizu: :kasui,
  )
end

def sake_create_6
  Sake.create!(
    alcohol: 16.0,
    aminosando: nil,
    aroma_impression: "弱い軽さあるりんご系",
    aroma_value: 1,
    awa: "",
    bindume_date: Date.new(2020, 8),
    bottle_level: :sealed,
    brew_year: Date.new(2019),
    color: "ほぼ無色",
    genryomai: "兵庫県産山田錦（１等米以上）",
    hiire: :mae_hiire,
    kakemai: "",
    kobo: "",
    kura: "平孝酒造株式会社",
    moto: :unknown,
    name: "純米秋あがり 日高見",
    nigori: "",
    nihonshudo: 2,
    note: "魚にはやっぱり日高見だっちゃ！",
    photos: [],
    price: 1540,
    roka: "",
    sando: nil,
    season: "ひやおろし",
    seimai_buai: 60,
    shibori: "",
    size: 720,
    taste_impression: "ロックのように軽やかな味わい。香りや酸で甘酸っぱさも少しあるけど、旨み中心の味。特にあとから旨味や苦味ががふわっと盛り上がるのが素敵。",
    taste_value: 2,
    todofuken: "宮城県",
    tokutei_meisho: :junmai,
    warimizu: :kasui,
  )
end

def sake_create_7
  Sake.create!(
    alcohol: 16.0,
    aminosando: nil,
    aroma_impression: "バナナ系の華やかな香り",
    aroma_value: 4,
    awa: "",
    bindume_date: Date.new(2020, 9),
    bottle_level: :sealed,
    brew_year: Date.new(2019),
    color: "やや黄色",
    genryomai: "",
    hiire: :mae_hiire,
    kakemai: "",
    kobo: "",
    kura: "合名会社川敬商店",
    moto: :yamahai,
    name: "山廃 純米原酒 黄金澤 ひやおろし",
    nigori: "",
    nihonshudo: nil,
    note: "食事がすすむすすむ。",
    photos: [],
    price: 1404,
    roka: "",
    sando: nil,
    season: "ひやおろし",
    seimai_buai: 60,
    shibori: "",
    size: 720,
    taste_impression: "口に入れると酸や複雑さがあり、急に山廃だと思い出される。しっかりした味だけど、落ち着きがあり嫌さがない綺麗さ。酸でキレもよい。",
    taste_value: 4,
    todofuken: "宮城県",
    tokutei_meisho: :junmai,
    warimizu: :genshu,
  )
end

def sake_create_8
  Sake.create!(
    alcohol: 16.0,
    aminosando: nil,
    aroma_impression: "酸もあるスッキリした林檎系の香り",
    aroma_value: 3,
    awa: "",
    bindume_date: Date.new(2020, 9),
    bottle_level: :sealed,
    brew_year: Date.new(2019),
    color: "瓶で黄色いけどコップではやや黄色",
    genryomai: "",
    hiire: :unknown,
    kakemai: "",
    kobo: "",
    kura: "萩野酒造株式会社",
    moto: :unknown,
    name: "萩の鶴 メガネ専用 全員メガネの蔵人で造りました 特別純米酒",
    nigori: "",
    nihonshudo: -2,
    note: "",
    photos: [],
    price: 3190,
    roka: "",
    sando: nil,
    season: "",
    seimai_buai: 60,
    shibori: "",
    size: 1800,
    taste_impression: "メガネ専用 全員メガネの蔵人で造りました 特別純米酒。瓶で黄色いけどコップではやや黄色。"\
                      "酸もあるスッキリした林檎系の香り。"\
                      "味もジューシーなりんごのような甘さをベースに、アルコールの辛さと旨さが少々ずつ。"\
                      "味は広がりがありゆっくり去っていく。山はきつくなく優しい。",
    taste_value: 4,
    todofuken: "宮城県",
    tokutei_meisho: :tokubetsu_junmai,
    warimizu: :kasui,
  )
end

def sake_create_9
  Sake.create!(
    alcohol: 15.0,
    aminosando: nil,
    aroma_impression: "香りは弱く淡い",
    aroma_value: 0,
    awa: "",
    bindume_date: Date.new(2020, 9),
    bottle_level: :sealed,
    brew_year: Date.new(2019),
    color: "ほぼ無色",
    genryomai: "ひだほまれ",
    hiire: :mae_hiire,
    kakemai: "",
    kobo: "",
    kura: "天領酒造株式会社",
    moto: :unknown,
    name: "日野屋 純米吟醸酒 飛騨産ひだほまれ60% 秋あがり",
    nigori: "",
    nihonshudo: 4,
    note: "もう一口と飲みたくなる美味さ。",
    photos: [],
    price: nil,
    roka: "",
    sando: nil,
    season: "秋あがり",
    seimai_buai: 60,
    shibori: "",
    size: 720,
    taste_impression: "味は旨口系で、旨味にほどよいバランスのヒネや酸味がある。どっしり系の味わいなのに強すぎず、柔らかさを感じられる。",
    taste_value: 5,
    todofuken: "岐阜県",
    tokutei_meisho: :junmai_ginjo,
    warimizu: :kasui,
  )
end

10_000.times do
  send("sake_create_#{rand(0..9)}")
end

# rubocop:enable Metrics/MethodLength, Naming/VariableNumber
