// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ShowTasteGraphController from "./show_taste_graph_controller"
application.register("show-taste-graph", ShowTasteGraphController)
