---
glob: "app/**/*.{html,text,js}{+*,}.erb"
EnableDefaultLinters: true
linters:
  DeprecatedClasses:
    enabled: true
  ErbSafety:
    enabled: true
  HardCodedString:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop-erb.yml
      # ERBでは<% %>が分離するため誤検知が多い
      # 以下、公式おすすめのオフ設定を持ってきた
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      # rubocop-erbの都合でオフにしたのをオンにする
      Layout/RedundantLineBreak:
        Enabled: true
  RequireScriptNonce:
    enabled: true
