excludes:
  # GitHub管理のactionsは信頼する
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: actions/checkout
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: actions/setup-node
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: actions/upload-artifact
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: github/codeql-action/*
