inherit_from:
  - https://raw.githubusercontent.com/cookpad/styleguide/5a2d036bd80c801678c76d133662d29d42247099/.rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.3
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*"
    # 以下デフォルト
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
  NewCops: enable               # 新規追加のPendingCopsを有効化

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# 文字列はダブルクオート
Style/StringLiterals:
  EnforcedStyle: double_quotes

# 先頭行のfrozen stringマジックコメントはなしでもよい
Style/FrozenStringLiteralComment:
  Enabled: false

# ドキュメント無しを許可
Style/Documentation:
  Enabled: false

# Arg/Array/Hashの最後のカンマを許可
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# テストファイルは長さ制限をなくす
Metrics/ClassLength:
  Exclude:
    - "**/*_test.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_test.rb"
    - "spec/**/*"

# rubocop-rspec

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - before
    - after
    - during
