inherit_from:
  - https://raw.githubusercontent.com/cookpad/styleguide/5a2d036bd80c801678c76d133662d29d42247099/.rubocop.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DisabledByDefault: false # Cookpad Styleguideの上書き
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*"
    # 以下デフォルト
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
  NewCops: enable # 新規追加のPendingCopsを有効化

# コメントをスペースで揃えるのを許す
Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

# テストファイルは長さ制限をなくす
Metrics/ClassLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

# メソッド名のエイリアスをつけるときは"alias"を使い、"alias_method"は使わない
# aliasの方が自由度は低いが安全であるため
Style/Alias:
  EnforcedStyle: prefer_alias

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# Cookpad Styleguideに従い、eachなどの手続き型スタイルではdo/endを、mapなどの関数型スタイルでは{}を使う
# 1ライナーで{}の使用を許可する
Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: true

# ドキュメント無しを許可
Style/Documentation:
  Enabled: false

# 先頭行のfrozen stringマジックコメントはなしでもよい
Style/FrozenStringLiteralComment:
  Enabled: false

# メソッド呼び出しのカッコの省略を禁止
# ただし、specとfactoryはDSLを使って良い
Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - "spec/**/*_spec.rb"
    - "spec/factories/*.rb"

# 文字列はダブルクオート
Style/StringLiterals:
  EnforcedStyle: double_quotes

# rubocop-rspec

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - before
    - after
    - during
