# fly.toml file generated for sakazuki on 2022-11-10T22:48:21+09:00

app = "sakazuki"
primary_region = "nrt"
swap_size_mb = 512

[build]
  dockerfile = "fly.Dockerfile"

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 8080
  force_https = true

[[http_service.checks]]
  grace_period = "5s"
  interval = "10s"
  method = "GET"
  timeout = "2s"
  path = "/sakes"
  protocol = "https"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
