# fly.toml app configuration file generated for sakazuki on 2025-03-30T19:16:47+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sakazuki"
primary_region = "nrt"
console_command = "/app/bin/rails console"
swap_size_mb = 512

[build]
  dockerfile = "fly.Dockerfile"

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  processes = ["app"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  timeout = "5s"
  method = "GET"
  path = "/up"
  protocol = "http"

[http_service.checks.headers]
  X-Forwarded-Proto = "https"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[vm]]
  size = "shared-cpu-1x"
