import "./autocompletion/complete_meigara.ts"
import "./sync_dom/sync_kura_todofuken.ts"
import "./sync_dom/sync_bindume_date.ts"
import "./taste_graph/input_taste_graph.ts"
import "./rating/rating.ts"
