name: "Auto Assign to PR Assignees"

on:
  pull_request:
    types: [opened, ready_for_review]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  add-reviews:
    name: add-reviews
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e
        with:
          configuration-path: ".github/auto_assign_configs.yml"
