name: Generic Checks

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: End of File with Newline
      run: ./cli-scripts/check_endoffile_with_newline.sh
    - name: Lint Dockerfile
      run: ./cli-scripts/run-hadolint.sh
