name: Test

on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read # Needed to read changes to skip test or not
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      # v4.0.1
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: filter
        with:
          filters: |
            src:
              - "app/**"
              - "spec/**"
              - "config/**"
              - "db/**"
              - "Gemfile"
              - "Gemfile.lock"
              - "package.json"
              - "yarn.lock"
              - ".ruby-version"
              - ".github/workflows/test.yml"

  test:
    name: test
    needs: changes
    if: needs.changes.outputs.src == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      postgres:
        # postgres:18.0-trixie
        image: postgres@sha256:6b8a8a9f35a6b4ac51e67ca9e73b16fb578155572055dcca32d75d1ed49045fa
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install --yes libvips
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
          cache: "yarn"
      - name: Install Yarn Dependencies
        run: yarn workspaces focus --all --production
      - name: Set up Ruby
        env:
          BUNDLE_WITHOUT: development
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455
        with:
          bundler-cache: true
      - name: Setup Database
        env:
          BUNDLE_WITHOUT: development
          RAILS_ENV: test
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Assets precompile
        env:
          BUNDLE_WITHOUT: development
          RAILS_ENV: test
        run: bundle exec rails assets:precompile
      - name: Run tests
        env:
          BUNDLE_WITHOUT: development
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
        run: bundle exec rspec

      - name: Upload code coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/capybara
          if-no-files-found: ignore
